package systemTesting.GRA;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;
public class RiconoscimentoModuloTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void riconoscimentoModulo() {
    driver.get("http://localhost:8080/EVIM-English-Validation-Internship-Management/");
    driver.manage().window().setSize(new Dimension(945, 1020));
    driver.findElement(By.id("bott")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("simonagrieco@studenti.unisa.it");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("grieco1998");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".item:nth-child(7)")).click();
    driver.findElement(By.linkText("Compila modulo riconoscimento")).click();
    driver.findElement(By.id("enteAzienda")).click();
    driver.findElement(By.id("enteAzienda")).sendKeys("HID GLOBAL");
    driver.findElement(By.id("indSede")).click();
    driver.findElement(By.id("indSede")).sendKeys("via giulio acciani");
    driver.findElement(By.id("prof")).click();
    driver.findElement(By.id("prof")).sendKeys("Sicurezza informatica");
    driver.findElement(By.cssSelector(".col-lg-6:nth-child(2)")).click();
    driver.findElement(By.name("tipoContratto")).sendKeys("stage 6 mesi");
    {
      WebElement element = driver.findElement(By.name("periodo"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.name("periodo"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.name("periodo"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.name("periodo")).click();
    driver.findElement(By.name("periodo")).sendKeys("21 Ottobre - 31 Dicembre");
    driver.findElement(By.id("oreSvolte")).click();
    driver.findElement(By.id("oreSvolte")).sendKeys("150");
    driver.findElement(By.id("sel3")).click();
    {
      WebElement dropdown = driver.findElement(By.id("sel3"));
      dropdown.findElement(By.xpath("//option[. = '6']")).click();
    }
    driver.findElement(By.id("sel3")).click();
    driver.findElement(By.cssSelector(".file-upload-btn1")).click();
    driver.findElement(By.name("file1[]")).sendKeys("C:\\fakepath\\a4 (1).pdf");
    driver.findElement(By.name("file2[]")).click();
    driver.findElement(By.name("file2[]")).sendKeys("C:\\fakepath\\Meeting_Agenda- 7_01_2020.pdf");
    driver.findElement(By.name("file3[]")).click();
    driver.findElement(By.name("file3[]")).sendKeys("C:\\fakepath\\Risultati I e II prova di IS.pdf");
    driver.findElement(By.id("bott-approva")).click();
    driver.close();
  }
}
